### ISSUE TITLE
3.0 Release checklist

### ISSUE THREAD

**Issue by scottkellum** [modularscale/modularscale-sass#128]
- [x] Check latest version of Ruby Sass compatability
- [x] Check latest version of LibSass compatability
- [x] Check Compass distribution
- [ ] Check Bower distribution
- [ ] Check Eyeglass distribution (#114)
- [ ] Check sache.in connection
